## Copyright © 2022, Oracle and/or its affiliates. 
## All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl

title: "Create typical three-node deployment of CockroachDB on Oracle Cloud Infrastructure Compute instances"
stackDescription: "Deploy typical three-node deployment of CockroachDB on Oracle Cloud Infrastructure Compute instances."
schemaVersion: 1.1.0
version: "20190404"
locale: "en"

variableGroups:
- title: General Configuration
  visible: false
  variables:
  - tenancy_ocid
  - region
  - release

- title: Required Configuration
  visible: true  
  variables:
  - compartment_ocid
  - availability_domain_name 
  - instance_count
  - show_advanced

- title: Networking Optional Configuration
  visible: 
      and:
        - show_advanced
  variables:  
  - VCN-CIDR
  - Subnet-CIDR

- title: Compute Optional Configuration
  visible: 
      and:
        - show_advanced
  variables:
  - ssh_public_key
  - instance_name
  - instance_shape
  - instance_flex_shape_ocpus
  - instance_flex_shape_memory
  - instance_os
  - linux_os_version

- title: Load Balancer Optional Configuration
  visible: 
      and:
        - show_advanced
  variables:
  - lb_shape
  - flex_lb_min_shape
  - flex_lb_max_shape 

variables:

  show_advanced:
    type: boolean
    title: "Show advanced options?"
    description: "Shows advanced options."
    visible: true
    default: false

  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    visibile: true
    title: Compartment
    description: "Compartment where you want to create the solution resources"

  region:
    type: oci:identity:region:name
    required: true
    visibile: true
    title: Region
    description: "Region where you want to deploy the resources defined by this stack."

  availability_domain_name:
    type: oci:identity:availabilitydomain:name
    required: true
    visibile: true
    title: "Availability Domain to be chosen"
    description: "Choose Availability Domain where your infrastructure will be deployed."
    dependsOn:
      regionName: ${region}
      compartmentId: ${compartment_ocid}

  instance_count:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 3
    title: "Cockroach DB nodes count"
    description: "Number of Cockroach DB nodes"

  # Optional Configuration
  VCN-CIDR:
    type: string
    required: false
    default: "10.0.0.0/16"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    description: "VCN CIDR block where you want to create the solution resources."

  Subnet-CIDR:
    type: string
    required: false
    default: "10.0.2.0/24"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    description: "Subnet's CIDR block where you want to place your CockroachDB nodes."

  ssh_public_key:
    type: oci:core:ssh:publickey
    title: "Public SSH Key"
    description: "Choose public SSH Key to be uploaded into compute instances."
    required: false

  instance_name:
    type: string
    required: false
    default: "cockroach"
    title: "CockroachDB node name"
    description: "Choose the name for CockroachDB node."

  instance_shape:
    type: oci:core:instanceshape:name
    required: false
    description: "Shape of the VM used for CockroachDB nodes."
    dependsOn:
      compartmentId: ${compartment_ocid}

  instance_flex_shape_ocpus:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "Flex Shape OCPUs"
    description: "Choose number of OCPUs for Flex Shape."
    visible:
      and:
        - or:
          - eq:
            - instance_shape 
            - "VM.Standard.E3.Flex"
          - eq:
            - instance_shape 
            - "VM.Standard.E4.Flex"

  instance_flex_shape_memory:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 10
    title: "Flex Shape Memory (GB)"
    description: "Choose number GB for Flex Shape Memory."
    visible:
      and:
        - or:
          - eq:
            - instance_shape 
            - "VM.Standard.E3.Flex"
          - eq:
            - instance_shape
            - "VM.Standard.E4.Flex"

  instance_os:
    type: enum
    required: false
    title: "Instance OS"
    description: "An Operating System that determines the operating system for the instance."
    default: "Oracle Linux"
    enum:
      - "Oracle Linux"
  
  linux_os_version:
    type: enum
    required: false
    title: "Instance OS version"
    description: "An Operating System version that determines the operating system version for the instance."
    default: "7.9"
    enum:
      - "7.9"
  
  lb_shape:
    type: enum
    title: "Load Balancer Shape"
    description: "Load Balancer Shape"
    default: "flexible"
    required: false 
    enum:
      - "flexible"
      - "100Mbps"
      - "10Mbps"
      - "10Mbps-Micro"
      - "400Mbps"
      - "8000Mbps"

  flex_lb_min_shape:
    type: enum
    required: false
    default: "10"
    title: "LB Flex Min Shape"
    description: "Choose Minimum Shape for Flex Load Balancer."
    enum:
      - "10"
      - "100"
      - "1000"
      - "400"
      - "8000"
    visible:
      and:
        - eq:
          - lb_shape 
          - "flexible"

  flex_lb_max_shape:
    type: enum
    required: false
    default: "100"
    title: "LB Flex Max Shape"
    description: "Choose Maximum Shape for Flex Load Balancer."
    enum:
      - "10"
      - "100"
      - "1000"
      - "400"
      - "8000"
    visible:
      and:
        - eq:
          - lb_shape 
          - "flexible"

outputs:
  
  loadbalancer_public_url:
    title: "LoadBalancer URL"
    displayText: "LoadBalancer URL"
    type: copyableString
    visible: true
  
  generated_ssh_private_key:
    title: "Generated SSH Private Key"
    displayText: "Generated SSH Private Key"
    type: string
    visible: true
